# Generated by Django 4.2.26 on 2025-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('BIZUM', 'Bizum')], default='EFECTIVO', max_length=20),
        ),
    ]
